//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirSvc.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://schemas.datacontract.org/2004/07/Lab07")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirSvc.ServiceReference1.Desempenho[] DesempenhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirSvc.ServiceReference1.Desempenho[] Desempenho {
            get {
                return this.DesempenhoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesempenhoField, value) != true)) {
                    this.DesempenhoField = value;
                    this.RaisePropertyChanged("Desempenho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Desempenho", Namespace="http://schemas.datacontract.org/2004/07/Lab07", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Desempenho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirSvc.ServiceReference1.Aluno AlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BimestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MareriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirSvc.ServiceReference1.Aluno Aluno {
            get {
                return this.AlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.AlunoField, value) != true)) {
                    this.AlunoField = value;
                    this.RaisePropertyChanged("Aluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((this.AnoField.Equals(value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bimestre {
            get {
                return this.BimestreField;
            }
            set {
                if ((object.ReferenceEquals(this.BimestreField, value) != true)) {
                    this.BimestreField = value;
                    this.RaisePropertyChanged("Bimestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mareria {
            get {
                return this.MareriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MareriaField, value) != true)) {
                    this.MareriaField = value;
                    this.RaisePropertyChanged("Mareria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicoAluno")]
    public interface IServicoAluno {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicoAluno/AddStudent")]
        void AddStudent(ConsumirSvc.ServiceReference1.Aluno student);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicoAluno/AddStudent")]
        System.Threading.Tasks.Task AddStudentAsync(ConsumirSvc.ServiceReference1.Aluno student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoAluno/GetAlunos", ReplyAction="http://tempuri.org/IServicoAluno/GetAlunosResponse")]
        ConsumirSvc.ServiceReference1.Aluno[] GetAlunos(bool showPerformance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoAluno/GetAlunos", ReplyAction="http://tempuri.org/IServicoAluno/GetAlunosResponse")]
        System.Threading.Tasks.Task<ConsumirSvc.ServiceReference1.Aluno[]> GetAlunosAsync(bool showPerformance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoAlunoChannel : ConsumirSvc.ServiceReference1.IServicoAluno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoAlunoClient : System.ServiceModel.ClientBase<ConsumirSvc.ServiceReference1.IServicoAluno>, ConsumirSvc.ServiceReference1.IServicoAluno {
        
        public ServicoAlunoClient() {
        }
        
        public ServicoAlunoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoAlunoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddStudent(ConsumirSvc.ServiceReference1.Aluno student) {
            base.Channel.AddStudent(student);
        }
        
        public System.Threading.Tasks.Task AddStudentAsync(ConsumirSvc.ServiceReference1.Aluno student) {
            return base.Channel.AddStudentAsync(student);
        }
        
        public ConsumirSvc.ServiceReference1.Aluno[] GetAlunos(bool showPerformance) {
            return base.Channel.GetAlunos(showPerformance);
        }
        
        public System.Threading.Tasks.Task<ConsumirSvc.ServiceReference1.Aluno[]> GetAlunosAsync(bool showPerformance) {
            return base.Channel.GetAlunosAsync(showPerformance);
        }
    }
}
