//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms.ClientServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoBairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoCEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoLogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoUFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgaoExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataExpedicao {
            get {
                return this.DataExpedicaoField;
            }
            set {
                if ((this.DataExpedicaoField.Equals(value) != true)) {
                    this.DataExpedicaoField = value;
                    this.RaisePropertyChanged("DataExpedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoBairro {
            get {
                return this.EnderecoBairroField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoBairroField, value) != true)) {
                    this.EnderecoBairroField = value;
                    this.RaisePropertyChanged("EnderecoBairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoCEP {
            get {
                return this.EnderecoCEPField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoCEPField, value) != true)) {
                    this.EnderecoCEPField = value;
                    this.RaisePropertyChanged("EnderecoCEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoCidade {
            get {
                return this.EnderecoCidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoCidadeField, value) != true)) {
                    this.EnderecoCidadeField = value;
                    this.RaisePropertyChanged("EnderecoCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoComplemento {
            get {
                return this.EnderecoComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoComplementoField, value) != true)) {
                    this.EnderecoComplementoField = value;
                    this.RaisePropertyChanged("EnderecoComplemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoLogradouro {
            get {
                return this.EnderecoLogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoLogradouroField, value) != true)) {
                    this.EnderecoLogradouroField = value;
                    this.RaisePropertyChanged("EnderecoLogradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoNumero {
            get {
                return this.EnderecoNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoNumeroField, value) != true)) {
                    this.EnderecoNumeroField = value;
                    this.RaisePropertyChanged("EnderecoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoUF {
            get {
                return this.EnderecoUFField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoUFField, value) != true)) {
                    this.EnderecoUFField = value;
                    this.RaisePropertyChanged("EnderecoUF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgaoExpedicao {
            get {
                return this.OrgaoExpedicaoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgaoExpedicaoField, value) != true)) {
                    this.OrgaoExpedicaoField = value;
                    this.RaisePropertyChanged("OrgaoExpedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCliente", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class GetCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable ClienteTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable ClienteTable {
            get {
                return this.ClienteTableField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteTableField, value) != true)) {
                    this.ClienteTableField = value;
                    this.RaisePropertyChanged("ClienteTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientServiceReference.IClientService")]
    public interface IClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Insert", ReplyAction="http://tempuri.org/IClientService/InsertResponse")]
        string Insert(WebForms.ClientServiceReference.Cliente client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Insert", ReplyAction="http://tempuri.org/IClientService/InsertResponse")]
        System.Threading.Tasks.Task<string> InsertAsync(WebForms.ClientServiceReference.Cliente client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Update", ReplyAction="http://tempuri.org/IClientService/UpdateResponse")]
        string Update(WebForms.ClientServiceReference.Cliente client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Update", ReplyAction="http://tempuri.org/IClientService/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(WebForms.ClientServiceReference.Cliente client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Delete", ReplyAction="http://tempuri.org/IClientService/DeleteResponse")]
        string Delete(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Delete", ReplyAction="http://tempuri.org/IClientService/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetInfo", ReplyAction="http://tempuri.org/IClientService/GetInfoResponse")]
        WebForms.ClientServiceReference.GetCliente GetInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetInfo", ReplyAction="http://tempuri.org/IClientService/GetInfoResponse")]
        System.Threading.Tasks.Task<WebForms.ClientServiceReference.GetCliente> GetInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetClienteRecords", ReplyAction="http://tempuri.org/IClientService/GetClienteRecordsResponse")]
        System.Data.DataSet GetClienteRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetClienteRecords", ReplyAction="http://tempuri.org/IClientService/GetClienteRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetClienteRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SearchClient", ReplyAction="http://tempuri.org/IClientService/SearchClientResponse")]
        System.Data.DataSet SearchClient(WebForms.ClientServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SearchClient", ReplyAction="http://tempuri.org/IClientService/SearchClientResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchClientAsync(WebForms.ClientServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetCep", ReplyAction="http://tempuri.org/IClientService/GetCepResponse")]
        string GetCep(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetCep", ReplyAction="http://tempuri.org/IClientService/GetCepResponse")]
        System.Threading.Tasks.Task<string> GetCepAsync(string cep);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : WebForms.ClientServiceReference.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.ClientBase<WebForms.ClientServiceReference.IClientService>, WebForms.ClientServiceReference.IClientService {
        
        public ClientServiceClient() {
        }
        
        public ClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insert(WebForms.ClientServiceReference.Cliente client) {
            return base.Channel.Insert(client);
        }
        
        public System.Threading.Tasks.Task<string> InsertAsync(WebForms.ClientServiceReference.Cliente client) {
            return base.Channel.InsertAsync(client);
        }
        
        public string Update(WebForms.ClientServiceReference.Cliente client) {
            return base.Channel.Update(client);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(WebForms.ClientServiceReference.Cliente client) {
            return base.Channel.UpdateAsync(client);
        }
        
        public string Delete(int Id) {
            return base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int Id) {
            return base.Channel.DeleteAsync(Id);
        }
        
        public WebForms.ClientServiceReference.GetCliente GetInfo() {
            return base.Channel.GetInfo();
        }
        
        public System.Threading.Tasks.Task<WebForms.ClientServiceReference.GetCliente> GetInfoAsync() {
            return base.Channel.GetInfoAsync();
        }
        
        public System.Data.DataSet GetClienteRecords() {
            return base.Channel.GetClienteRecords();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetClienteRecordsAsync() {
            return base.Channel.GetClienteRecordsAsync();
        }
        
        public System.Data.DataSet SearchClient(WebForms.ClientServiceReference.Cliente cliente) {
            return base.Channel.SearchClient(cliente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchClientAsync(WebForms.ClientServiceReference.Cliente cliente) {
            return base.Channel.SearchClientAsync(cliente);
        }
        
        public string GetCep(string cep) {
            return base.Channel.GetCep(cep);
        }
        
        public System.Threading.Tasks.Task<string> GetCepAsync(string cep) {
            return base.Channel.GetCepAsync(cep);
        }
    }
}
