using System;
using System.Collections.Generic;
using System.Text;
using Varsis.Data.Infrastructure;
using static Varsis.Data.Model.Integration.Invoice;

namespace Varsis.Data.Model.Integration
{
    public class CadItem : EntityBase
    {
        public enum CadItemIntegrationStatus
        {
            Importing = 0,
            Created = 1,
            Processed = 2,
            Error = 99
        }
        public int DEPTO { get; set; }
        public int SECAO { get; set; }
        public int GRUPO { get; set; }
        public int SUBGRUPO { get; set; }
        public int CATEGORIA { get; set; }
        public int COD_FOR { get; set; }
        public int COD_ITEM { get; set; }
        public int DIGITO { get; set; }
        public long CODIGO_PAI { get; set; }
        public long CODIGO_EAN13 { get; set; }
        public string DESCRICAO { get; set; }
        public string DESC_REDUZ { get; set; }
        public string DESC_COML { get; set; }
        public string REFERENCIA { get; set; }
        public int EMB_FOR { get; set; }
        public string TPO_EMB_FOR { get; set; }
        public long EAN_EMB_FOR { get; set; }
        public int EMB_TRANSF { get; set; }
        public string TPO_EMB_TRANSF { get; set; }
        public long EAN_EMB_TRANSF { get; set; }
        public int EMB_VENDA { get; set; }
        public string TPO_EMB_VENDA { get; set; }
        public long EAN_EMB_VENDA { get; set; }
        public int TIPO_PALLET { get; set; }
        public int BASE_PALLET { get; set; }
        public int ALTURA_PALLET { get; set; }
        public long COMPRIMENTO_EMB { get; set; }
        public long COMPR_EMB_TRF { get; set; }
        public long COMPR_EMB_VND { get; set; }
        public long LARGURA_EMB { get; set; }
        public long LARGURA_EMB_TRF { get; set; }
        public long LARGURA_EMB_VND { get; set; }
        public long ALTURA_EMB { get; set; }
        public long ALTURA_EMB_TRF { get; set; }
        public long ALTURA_EMB_VND { get; set; }
        public int TIPO_PLU { get; set; }
        public long PESO { get; set; }
        public long PESO_TRF { get; set; }
        public long PESO_VND { get; set; }
        public long DEPOSITO { get; set; }
        public string LINHA { get; set; }
        public string CLASSE { get; set; }
        public string POLIT_PRE { get; set; }
        public int SIS_ABAST { get; set; }
        public int PRZ_ENTRG { get; set; }
        public int DIA_VISIT { get; set; }
        public int FRQ_VISIT { get; set; }
        public int TIPO_ETQ { get; set; }
        public int TIPO_PRO { get; set; }
        public int COMPRADOR { get; set; }
        public int COND_PGTO { get; set; }
        public int COND_PGTO_ANT { get; set; }
        public int COND_PGTO_MAN { get; set; }
        public int CDPG_VDA { get; set; }
        public int TIPO_ETQ_GON { get; set; }
        public string COR { get; set; }
        public int DAT_ENT_LIN { get; set; }
        public int DAT_SAI_LIN { get; set; }
        public int NAT_FISCAL { get; set; }
        public string ESTADO { get; set; }
        public int COD_PAUTA { get; set; }
        public long PERC_IPI { get; set; }
        public int QTDE_ETQ_GON { get; set; }
        public long PERC_BONIF { get; set; }
        public long PERC_BONIF_ANT { get; set; }
        public long PERC_BONIF_MAN { get; set; }
        public int ENTREGA { get; set; }
        public long FRETE { get; set; }
        public long CUS_FOR { get; set; }
        public long CUSF_ANT { get; set; }
        public long CUSF_MAN { get; set; }
        public int DAT_CUS_FOR { get; set; }
        public int DAT_CUSF_ANT { get; set; }
        public int DAT_CUSF_MAN { get; set; }
        public long DESP_ACES { get; set; }
        public long DESP_ACES_ANT { get; set; }
        public long DESP_ACES_MAN { get; set; }
        public long CUS_REP { get; set; }
        public long CUSR_ANT { get; set; }
        public long CUSR_MAN { get; set; }
        public int DAT_CUS_REP { get; set; }
        public int DAT_CUSR_ANT { get; set; }
        public int DAT_CUSR_MAN { get; set; }
        public long CUS_MED { get; set; }
        public long CUSM_ANT { get; set; }
        public long CUSM_MAN { get; set; }
        public int DAT_CUS_MED { get; set; }
        public int DAT_CUSM_ANT { get; set; }
        public int DAT_CUSM_MAN { get; set; }
        public long CUS_MED_C { get; set; }
        public int DAT_CUS_MED_C { get; set; }
        public long PRC_VEN_1 { get; set; }
        public long PRCV_ANT_1 { get; set; }
        public long PRCV_MAN_1 { get; set; }
        public int MRG_LUCRO_1 { get; set; }
        public int DSC_MAX_1 { get; set; }
        public long COMISSAO_1 { get; set; }
        public int DAT_PRC_VEN_1 { get; set; }
        public int DAT_PRCV_ANT_1 { get; set; }
        public int DAT_PRCV_MAN_1 { get; set; }
        public long PRC_VEN_2 { get; set; }
        public long PRCV_ANT_2 { get; set; }
        public long PRCV_MAN_2 { get; set; }
        public int MRG_LUCRO_2 { get; set; }
        public int DSC_MAX_2 { get; set; }
        public long COMISSAO_2 { get; set; }
        public int DAT_PRC_VEN_2 { get; set; }
        public int DAT_PRCV_ANT_2 { get; set; }
        public int DAT_PRCV_MAN_2 { get; set; }
        public long PRC_VEN_3 { get; set; }
        public long PRCV_ANT_3 { get; set; }
        public long PRCV_MAN_3 { get; set; }
        public int MRG_LUCRO_3 { get; set; }
        public int DSC_MAX_3 { get; set; }
        public long COMISSAO_3 { get; set; }
        public int DAT_PRC_VEN_3 { get; set; }
        public int DAT_PRCV_ANT_3 { get; set; }
        public int DAT_PRCV_MAN_3 { get; set; }
        public long PRC_VEN_4 { get; set; }
        public long PRCV_ANT_4 { get; set; }
        public long PRCV_MAN_4 { get; set; }
        public int MRG_LUCRO_4 { get; set; }
        public int DSC_MAX_4 { get; set; }
        public long COMISSAO_4 { get; set; }
        public int DAT_PRC_VEN_4 { get; set; }
        public int DAT_PRCV_ANT_4 { get; set; }
        public int DAT_PRCV_MAN_4 { get; set; }
        public long PRC_VEN_5 { get; set; }
        public long PRCV_ANT_5 { get; set; }
        public long PRCV_MAN_5 { get; set; }
        public int MRG_LUCRO_5 { get; set; }
        public int DSC_MAX_5 { get; set; }
        public long COMISSAO_5 { get; set; }
        public int DAT_PRC_VEN_5 { get; set; }
        public int DAT_PRCV_ANT_5 { get; set; }
        public int DAT_PRCV_MAN_5 { get; set; }
        public int TIP_OFT_1 { get; set; }
        public int TIP_OFT_ANT_1 { get; set; }
        public int INI_OFT_1 { get; set; }
        public int INI_OFT_ANT_1 { get; set; }
        public int FIM_OFT_1 { get; set; }
        public int FIM_OFT_ANT_1 { get; set; }
        public long PRC_OFT_1 { get; set; }
        public long PRC_OFT_ANT_1 { get; set; }
        public int LIM_OFT_1 { get; set; }
        public int LIM_OFT_ANT_1 { get; set; }
        public int SAL_OFT_1 { get; set; }
        public int SAL_OFT_ANT_1 { get; set; }
        public int TIP_OFT_2 { get; set; }
        public int TIP_OFT_ANT_2 { get; set; }
        public int INI_OFT_2 { get; set; }
        public int INI_OFT_ANT_2 { get; set; }
        public int FIM_OFT_2 { get; set; }
        public int FIM_OFT_ANT_2 { get; set; }
        public long PRC_OFT_2 { get; set; }
        public long PRC_OFT_ANT_2 { get; set; }
        public int LIM_OFT_2 { get; set; }
        public int LIM_OFT_ANT_2 { get; set; }
        public int SAL_OFT_2 { get; set; }
        public int SAL_OFT_ANT_2 { get; set; }
        public int TIP_OFT_3 { get; set; }
        public int TIP_OFT_ANT_3 { get; set; }
        public int INI_OFT_3 { get; set; }
        public int INI_OFT_ANT_3 { get; set; }
        public int FIM_OFT_3 { get; set; }
        public int FIM_OFT_ANT_3 { get; set; }
        public long PRC_OFT_3 { get; set; }
        public long PRC_OFT_ANT_3 { get; set; }
        public int LIM_OFT_3 { get; set; }
        public int LIM_OFT_ANT_3 { get; set; }
        public int SAL_OFT_3 { get; set; }
        public int SAL_OFT_ANT_3 { get; set; }
        public int TIP_OFT_4 { get; set; }
        public int TIP_OFT_ANT_4 { get; set; }
        public int INI_OFT_4 { get; set; }
        public int INI_OFT_ANT_4 { get; set; }
        public int FIM_OFT_4 { get; set; }
        public int FIM_OFT_ANT_4 { get; set; }
        public long PRC_OFT_4 { get; set; }
        public long PRC_OFT_ANT_4 { get; set; }
        public int LIM_OFT_4 { get; set; }
        public int LIM_OFT_ANT_4 { get; set; }
        public int SAL_OFT_4 { get; set; }
        public int SAL_OFT_ANT_4 { get; set; }
        public int TIP_OFT_5 { get; set; }
        public int TIP_OFT_ANT_5 { get; set; }
        public int INI_OFT_5 { get; set; }
        public int INI_OFT_ANT_5 { get; set; }
        public int FIM_OFT_5 { get; set; }
        public int FIM_OFT_ANT_5 { get; set; }
        public long PRC_OFT_5 { get; set; }
        public long PRC_OFT_ANT_5 { get; set; }
        public int LIM_OFT_5 { get; set; }
        public int LIM_OFT_ANT_5 { get; set; }
        public int SAL_OFT_5 { get; set; }
        public int SAL_OFT_ANT_5 { get; set; }
        public int INI_BONUS { get; set; }
        public int INI_BONUS_ANT { get; set; }
        public int FIM_BONUS { get; set; }
        public long PRES_ENT { get; set; }
        public long PRC_BONUS { get; set; }
        public long PRES_REP { get; set; }
        public long ESTQ_ATUAL { get; set; }
        public long ESTQ_DP { get; set; }
        public long ESTQ_LJ { get; set; }
        public long QDE_PEND { get; set; }
        public long CUS_INV { get; set; }
        public long ESTQ_PADRAO { get; set; }
        public int SAI_MED_CAL { get; set; }
        public string TAMANHO { get; set; }
        public long SAI_ACM_UN { get; set; }
        public long SAI_ACM_CUS { get; set; }
        public long SAI_ACM_VEN { get; set; }
        public long CUS_ULT_ENT_BRU { get; set; }
        public long ENT_ACM_UN { get; set; }
        public long ENT_ACM_CUS { get; set; }
        public int DAT_ULT_FAT { get; set; }
        public long ULT_QDE_FAT { get; set; }
        public long ULT_QDE_ENT { get; set; }
        public long CUS_ULT_ENT { get; set; }
        public int DAT_ULT_ENT { get; set; }
        public long ABC_F { get; set; }
        public long ABC_S { get; set; }
        public long ABC_T { get; set; }
        public string PERECIVEL { get; set; }
        public int PRZ_VALIDADE { get; set; }
        public int TOT_PEDIDO { get; set; }
        public int TOT_FALTA { get; set; }
        public int COD_VAS { get; set; }
        public int DIG_VAS { get; set; }
        public int COD_ENG { get; set; }
        public int DIG_ENG { get; set; }
        public long VALOR_IPI { get; set; }
        public long VALOR_IPI_ANT { get; set; }
        public long VALOR_IPI_MAN { get; set; }
        public long CLASS_FIS { get; set; }
        public string QTD_AUT_PDV { get; set; }
        public int MOEDA_VDA { get; set; }
        public int BONI_MERC { get; set; }
        public int BONI_MERC_ANT { get; set; }
        public int BONI_MERC_MAN { get; set; }
        public string GRADE { get; set; }
        public int MENS_AUX { get; set; }
        public int PROCEDENCIA { get; set; }
        public int CATEGORIA_ANT { get; set; }
        public int ESTRATEGIA_REP { get; set; }
        public long DESP_ACES_ISEN { get; set; }
        public long DESP_ACES_ISEN_ANT { get; set; }
        public long DESP_ACES_ISEN_MAN { get; set; }
        public long FRETE_VALOR { get; set; }
        public long FRETE_VALOR_ANT { get; set; }
        public long FRETE_VALOR_MAN { get; set; }
        public long BONIF_PER { get; set; }
        public long BONIF_PER_ANT { get; set; }
        public long BONIF_PER_MAN { get; set; }
        public string VASILHAME { get; set; }
        public string PERMITE_DESC { get; set; }
        public string QTD_OBRIG { get; set; }
        public string ENVIA_PDV { get; set; }
        public string ENVIA_BALANCA { get; set; }
        public string PESADO_PDV { get; set; }
        public string JPMA_FLAG1 { get; set; }
        public string JPMA_FLAG2 { get; set; }
        public string JPMA_FLAG3 { get; set; }
        public string LINHA_ANTERIOR { get; set; }
        public int LINHA_VALIDA { get; set; }
        public int QUANT_EAN { get; set; }
        public int TOT_ESTOCADO { get; set; }
        public int EMPIL_MAX { get; set; }
        public int TIPO_END { get; set; }
        public string SAZONAL { get; set; }
        public string MARCA_PROP { get; set; }
        public long FILLER { get; set; }
        public DateTime LASTUPDATE { get; set; }
        public CadItemIntegrationStatus status { get; set; }
    }
}
