using System;
using System.Collections.Generic;
using System.Text;
using Varsis.Data.Infrastructure;

namespace Varsis.Data.Model.Integration
{
    public class VSITITEM : EntityBase
    {
        public override string EntityName => "Cadastro de VSITITEM";
        public enum VSITITEMIntegrationStatus { Importing = 0, Created = 1, Processed = 2, Error = 99 }
        public string lastupdate { get; set; }
        public string data_inclusao { get; set; }
        public string data_integracao { get; set; }
        public VSITITEMIntegrationStatus status { get; set; }
        public double? cof_alq { get; set; }
        public double? iss_val { get; set; }
        public double? cus_uni { get; set; }
        public double? pis_ctb { get; set; }
        public double? tfi_std { get; set; }
        public double? dfo_alq { get; set; }
        public double? ins_alq { get; set; }
        public long? tfi_cst { get; set; }
        public long? cod_ctr { get; set; }
        public double? fcs_alq { get; set; }
        public double? val_uni_fst { get; set; }
        public long? nat_rec { get; set; }
        public double? iss_alq { get; set; }
        public double? val_uni_fst_cpl { get; set; }
        public string t06_ctb { get; set; }
        public double? vlr_pau { get; set; }
        public long? tip_cre { get; set; }
        public double? icm_ori { get; set; }
        public double? val_uni_icm_ope { get; set; }
        public double? pir_bas { get; set; }
        public double? dfd_alq { get; set; }
        public double? cof_bas { get; set; }
        public double? ipi_adi { get; set; }
        public double? ips_alq { get; set; }
        public long? cof_cst { get; set; }
        public double? fnt_ffi { get; set; }
        public double? bas_uni_ist { get; set; }
        public double? val_uni_fst_res { get; set; }
        public double? pis_bas { get; set; }
        public long? cof_sit { get; set; }
        public double? cor_alq { get; set; }
        public double? fcp_alq { get; set; }
        public double? ins_val { get; set; }
        public double? fcr_val { get; set; }
        public double? fps_val { get; set; }
        public double? pis_alq { get; set; }
        public double? val_uni_icm_est { get; set; }
        public double? val_uni_ist_res { get; set; }
        public long? ipi_cst { get; set; }
        public string t27_csl { get; set; }
        public double? val_uni_icm { get; set; }
        public double? csl_alq { get; set; }
        public double? cpl_trb { get; set; }
        public long? seq { get; set; }
        public string cod_mot { get; set; }
        public double? dfo_bas { get; set; }
        public double? csl_val { get; set; }
        public double? fps_bas { get; set; }
        public double? fcp_val { get; set; }
        public string t18_ipi { get; set; }
        public double? fcs_val { get; set; }
        public string sit { get; set; }
        public double? icm_out { get; set; }
        public double? icm_dif { get; set; }
        public double? dfd_bas { get; set; }
        public double? fnt_dif { get; set; }
        public string t19_irf { get; set; }
        public double? mer_val { get; set; }
        public double? tfi_str { get; set; }
        public long? pis_cat { get; set; }
        public double? pir_alq { get; set; }
        public double? des_alq { get; set; }
        public double? fps_alq { get; set; }
        public long? tfi_ope { get; set; }
        public double? tfi_rdz { get; set; }
        public string t26_iss { get; set; }
        public double? fcp_bas { get; set; }
        public double? dfd_val { get; set; }
        public double? dsp_fin { get; set; }
        public long? bas_emb { get; set; }
        public double? icm_red { get; set; }
        public long? pis_cst { get; set; }
        public double? csl_bas { get; set; }
        public double? ipi_dif { get; set; }
        public double? icm_ise { get; set; }
        public double? pir_val { get; set; }
        public double? icm_val { get; set; }
        public double? icm_str { get; set; }
        public string t25_pis { get; set; }
        public double? fcs_bas { get; set; }
        public double? eft_val { get; set; }
        public double? fun_alq { get; set; }
        public double? pvv_gre { get; set; }
        public double? qtd_uni { get; set; }
        public long? pis_sit { get; set; }
        public double? ctb_dif { get; set; }
        public double? icm_alq { get; set; }
        public double? tfi_rdf { get; set; }
        public double? fnt_gre { get; set; }
        public double? pvv_adi { get; set; }
        public long? sec { get; set; }
        public double? tfi_fnt { get; set; }
        public double? ips_bas { get; set; }
        public double? fnt_alq { get; set; }
        public double? fun_val { get; set; }
        public double? irf_val { get; set; }
        public double? ins_bas { get; set; }
        public double? bas_ori { get; set; }
        public double? icm_ntr { get; set; }
        public double? ips_val { get; set; }
        public double? cpl_ise { get; set; }
        public double? bas_dif { get; set; }
        public double? des_val { get; set; }
        public double? eft_bas { get; set; }
        public double? dsc_trb { get; set; }
        public double? des_bas { get; set; }
        public double? cof_val { get; set; }
        public double? irf_alq { get; set; }
        public string t23_ins { get; set; }
        public double? dsc_ise { get; set; }
        public double? icm_bas { get; set; }
        public string t05_rec { get; set; }
        public string t07_est { get; set; }
        public double? fcr_alq { get; set; }
        public long? cof_cat { get; set; }
        public string dcr { get; set; }
        public string t08_cst { get; set; }
        public double? cor_val { get; set; }
        public double? qtd_fat { get; set; }
        public double? eft_red { get; set; }
        public double? val_uni_ist_cpl { get; set; }
        public long? age { get; set; }
        public double? prc_emb { get; set; }
        public double? fcr_bas { get; set; }
        public double? crd_pre { get; set; }
        public double? pvv_ffi { get; set; }
        public double? val_uni_ist { get; set; }
        public long? cfo { get; set; }
        public long? icm_fro { get; set; }
        public long? icm_cst { get; set; }
        public long? tfi_spn { get; set; }
        public long? gre { get; set; }
        public double? pvv_val { get; set; }
        public string t01_pag { get; set; }
        public double? ipi_val { get; set; }
        public double? alq_ori { get; set; }
        public double? dfo_val { get; set; }
        public double? pis_val { get; set; }
        public double? ise_dif { get; set; }
        public long? crf { get; set; }
        public double? ctb_val { get; set; }
        public long? icm_ope { get; set; }
        public double? cof_ctb { get; set; }
        public double? cor_bas { get; set; }
        public double? cpl_val { get; set; }
        public double? fnt_adi { get; set; }
        public long? id { get; set; }
        public double? ipi_bas { get; set; }
        public double? seg_val { get; set; }
        public double? dif_val { get; set; }
        public string ite { get; set; }
        public long? fig { get; set; }
        public double? eft_alq { get; set; }
        public string tpo_emb { get; set; }
        public double? frt_val { get; set; }
        public double? tfi_icm { get; set; }
        public double? fnt_val { get; set; }
        public double? irf_bas { get; set; }
        public long? nat_cre { get; set; }
        public double? ipi_alq { get; set; }
        public double? iss_bas { get; set; }
    }
}
